export const FETCH_CATEGORIES_BEGIN   = 'FETCH_CATEGORIES_BEGIN';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const FETCH_POSTS_BEGIN   = 'FETCH_POSTS_BEGIN';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const SORT_BY_NEW = 'SORT_BY_NEW';
export const SORT_BY_OLD = 'SORT_BY_OLD';
export const SORT_BY_HIGHEST_VOTE = 'SORT_BY_HIGHEST_VOTE';
export const SORT_BY_LOWEST_VOTE = 'SORT_BY_LOWEST_VOTE';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_CANCEL = 'DELETE_POST_CANCEL';

export const DELETE_POST_BEGIN = 'DELETE_POST_BEGIN';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

//export const VOTE_POST ='VOTE_POST';
export const VOTE_POST_BEGIN ='VOTE_POST_BEGIN';
export const VOTE_POST_TO_SERVER_SUCCESS = 'VOTE_POST_TO_SERVER_SUCCESS';
export const VOTE_POST_TO_SERVER_ERROR = 'VOTE_POST_TO_SERVER_ERROR';

export const VOTE_COMMENT_BEGIN ='VOTE_COMMENT_BEGIN';
export const VOTE_COMMENT_TO_SERVER_SUCCESS = 'VOTE_COMMENT_TO_SERVER_SUCCESS';
export const VOTE_COMMENT_TO_SERVER_ERROR = 'VOTE_COMMENT_TO_SERVER_ERROR';

//export const ADD_POST_REQUEST ='ADD_POST_REQUEST';

export const ADD_POST_BEGIN ='ADD_POST_BEGIN';
export const ADD_POST_TO_SERVER_SUCCESS ='ADD_POST_TO_SERVER_SUCCESS';
export const ADD_POST_TO_SERVER_ERROR ='ADD_POST_TO_SERVER_ERROR';
