export const FETCH_CATEGORIES_BEGIN   = 'FETCH_CATEGORIES_BEGIN';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const FETCH_POSTS_BEGIN   = 'FETCH_POSTS_BEGIN';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const SORT_BY_NEW = 'SORT_BY_NEW';
export const SORT_BY_OLD = 'SORT_BY_OLD';
export const SORT_BY_HIGHEST_VOTE = 'SORT_BY_HIGHEST_VOTE';
export const SORT_BY_LOWEST_VOTE = 'SORT_BY_LOWEST_VOTE';
